### ISSUE TITLE
Creating programs/scripts for plotting and summary statistics

### ISSUE THREAD

**Issue by morriscb** [LSSTDESC/PZDC1paper#1]
Created a branch of this repository for developing summary programs/scripts for plotting and computing summary statistics for the paper (https://github.com/LSSTDESC/PZDC1paper/tree/pz_metrics). We are using the `qp` package to ingest the redshift PDFs and perform computations.

Those interested in working on these scripts should contribute to this branch.

**Comment by aimalz** [comment]
For these scripts, a good format would be to write skeleton versions of the scripts the DC1 paper needs with detailed docstrings for any functions that don't exist yet.  Then please make an issue for [`qp`](https://github.com/aimalz/qp) telling me what features to prioritize adding (or start a branch implementing those functions -- you might want to start from the [branch](https://github.com/aimalz/qp/tree/issue/43/survey_mode) where I'm developing the `qp.ensemble` class for catalogs of photo-z PDFs).  

Also, @sschmidt23, in the repository settings, you should be able to add the entire PZWG to the repo.  Alternatively, an email to the PZWG might be useful just to let people know this repo exists and that there will be active development on Hack Day.

**Comment by sschmidt23** [comment]
I added the "PZ team", which only has 8 members.  I'll send an email as well, to let others know that you will be working on this during the hack day.

**Comment by morriscb** [comment]
KLD is calculable currently with a wrapped qp and stacked LePHARE data. KLD vs true spec N(z) is 0.14. First qp outputs which script:

![download](https://user-images.githubusercontent.com/3270927/28226670-0001d578-68a5-11e7-99b0-3d9550a6e3c6.png)

**Comment by sschmidt23** [comment]
I was playing with the qp.Ensemble stuff to try to get KLD working with BPZ, I managed to get a number using qp.utils.calculate_kl_divergence, but didn't get Ensemble.kld to work.  I have a couple questions.  I uploaded an ipynb which you can see here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/BPZ%20KLD%20test.ipynb

So I created a stack of all the 111k BPZ p(z)'s with 
sumpdf = approx_pdf.stack(loc=newarray,using='gridded',vb=True)
but, I was getting errors when trying to do sumpdf.kld(), so instead I output a grid of values for the stack and created a new PDF object, then just used the qp.utils.calculate_kl_divergence.  

One thing that puzzles me: when I create a PDF object from the spec-z's and reading the spec-z's in as samples with:
true_pdf = qp.PDF(samples=z_trues)
if I try to evaluate the pdf outside the support of the spec-z's (which span 0.016<=z<=2), I get 'NaN'.  I just created some samples and checked them, so maybe there are some bad values in my specz file or something.  I'll continue looking in to this.

Chris, can you upload a notebook that shows how you got LePhare results?  And what points did you evaluate it the KLD on?  Unfortunately, I think the values will depend on the grid on which we evaluate it, so we'll have to think carefully about this.

**Comment by sschmidt23** [comment]
One other thing: the dataset that we sent everyone contains galaxies down to i<26.9, but we only want to evaluate the i<25.3 sample.  I haven't made those cuts yet to see how different the results look.  We do need to keep track of i-band magnitude to make those cuts, though, or at least the IDs of the galaxies in vs out of Gold sample.
