### ISSUE TITLE
Create working script for calculating moments of the distributions?

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#10]
Has this script been finalized?
Has it been uploaded to the PZDC1paper repository?

**Comment by aimalz** [comment]
This is now built into [`qp`](https://github.com/aimalz/qp), with a demo of how to call the function in cell 13 [here](https://htmlpreview.github.io/?https://github.com/aimalz/qp/blob/master/docs/desc-0000-qp-photo-z_approximation/research/analysis.html).

**Comment by cavuoti** [comment]
Dear Alex, 
I was trying to run the notebook: qp/docs/desc-0000-qp-photo-z_approximation/research/analysis.ipynb

at the cell 18 (# the "pipeline") I get the error tha you can see here:
![screen](https://user-images.githubusercontent.com/23360794/31384458-60ab1510-adbf-11e7-86e5-7122f6726f0d.png)

do you have any idea of how can I solve this?

**Comment by aimalz** [comment]
@cavuoti Thanks for bringing up this new (to me) error.  The `GaussianMixture` class is from [scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html).  I have only run my tests with version 0.18.0 locally and 0.19.0 on NERSC.  What version do you have?  I can try testing with that one to see if it's the problem.  If you do upgrade to 0.18.0 or 0.19.0 (or run it on NERSC), make sure to reinstall `qp` using the `setup.py` (or with `python /global/homes/a/aimalz/qp/setup.py install --user` on NERSC) after the update and restart your Jupyter kernel before trying again.  Please let me know via an [Issue](https://github.com/aimalz/qp/issues) on `qp` if this doesn't fix the problem.

**Comment by jbkalmbach** [comment]
Is this something that still needs to be done? I add a script in the repo that translates Alex's code from that notebook if that would be useful?

**Comment by cavuoti** [comment]
@aimalz I had the version 0.17, with the 0.19 it is running, thanks a lot

**Comment by cavuoti** [comment]
@jbkalmbach if you can perform some test in order to verify that everything is going right with this code it would be great

**Comment by aimalz** [comment]
This looks like it was solved a long time ago, so I'm closing the issue.
