### ISSUE TITLE
Create working script for Anderson-Darling test?

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#11]
Has this script been finalized?
Has it been uploaded to the PZDC1paper repository?

**Comment by sschmidt23** [comment]
I wrote some kludgey code [here](https://github.com/LSSTDESC/PZDC1paper/blob/pz_metrics/metric_scripts/individual_metrics.py) to to do the the KS, CvM and AD tests for N(z) distributions using the skgof functions that Rongpu used in his p(z) tests.  I made a quick notebook to check the values for a known distribution, a simple sum of two Gaussians.  KS and CvM I think look good.  But, if you look at the p-value for the Anderson Darling test, it is 1.e-8, but the samples are drawn from two Gaussians.  If you draw from a single Gaussian you get a decent p-value for this test.  @aimalz do you have any thoughts on this?
Example notebook showing the behavior is here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/nz_stats_fakedatatest.ipynb

**Comment by sschmidt23** [comment]
I made a notebook for the exact same two Gaussian test for the p(z) versions of KS, CvM, and AD tests (which compare the PIT values to a uniform distribution) , once again KS and CvM look ok, and once again the AD p-value is tiny:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest.ipynb

**Comment by janewman-pitt-edu** [comment]
Does the p-value change if you change the gridding? (A-D gives large weights to tails, and so changing the gridding or using Gaussians that don't quite get to zero before the edges of your grid could affect things, I think).

**Comment by aimalz** [comment]
If the KS and CvM look okay, then (for once) it's probably not a bug in `qp`.  Where does `skgof` live?  I can take a look and see if it's somehow triggering unexpected behavior with `qp`.

**Comment by sschmidt23** [comment]
@janewman-pitt-edu the way it is currently implemented, the skgof package is handling the integration internally, so I'm not sure how it handles the tails.  It seems to be doing some k-sample variation, rather than comparison of two distributions, as it takes a set of k numbers and a continuous distribution.  This is the case for all 3 of KS, CvM, and AD: for p(z)  Rongpu feeds it the PIT values and the scipy.stats.uniform distribution; for the N(z) case I feed it the spec-z values and for the continuous distribution I output a qp.ensemble.stack of the k p(z)'s on a grid, create a separate qp.PDF object for that (wrapped in a class that has .pdf() and .cdf() methods) to compare against.

@aimalz the skgof code can be found here: https://pypi.python.org/pypi/scikit-gof
As I said, I haven't dug into the code at all to see how it works, @rongpu used it in the p(z) KS, CvM, and AD tests, so I just basically copied that for the N(z) case.

I also tried the scipy.stats.anderson_ksamp(sample1,sample2) function [link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html), which tests if two samples are drawn from the same distribution.  I tried comparing values drawn from the two Gaussians I used in my ipynb example and somehow got a negative value for the statistic, which panicked the p-value calculator and caused a math overflow because the p-value was greater than 10^4032, so I kinda have my doubts about that method for non-trivial distributions as well...

**Comment by janewman-pitt-edu** [comment]
You'll find that a lot of codes out there calculate p-values appropriate
only for certain distributions... Rongpu put some effort into finding more
general results.

jeff

On Thu, Sep 14, 2017 at 12:43 AM, Sam Schmidt <notifications@github.com>
wrote:

> @janewman-pitt-edu
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjanewman-pitt-edu&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=uEWp5KgLEEHaLK4PkFiWvAO2%2BaryGxCHxSNAtw80D2U%3D&reserved=0>
> the way it is currently implemented, the skgof package is handling the
> integration internally, so I'm not sure how it handles the tails. It seems
> to be doing some k-sample variation, rather than comparison of two
> distributions, as it takes a set of k numbers and a continuous
> distribution. This is the case for all 3 of KS, CvM, and AD: for p(z)
> Rongpu feeds it the PIT values and the scipy.stats.uniform distribution;
> for the N(z) case I feed it the spec-z values and for the continuous
> distribution I output a qp.ensemble.stack of the k p(z)'s on a grid, create
> a separate qp.PDF object for that (wrapped in a class that has .pdf() and
> .cdf() methods) to compare against.
>
> @aimalz
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faimalz&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=Df3NwS8s0gnsnVPliFUichSV%2BbEBxE7cAQtxY9pSHZA%3D&reserved=0>
> the skgof code can be found here: https://pypi.python.org/pypi/scikit-gof
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpypi.python.org%2Fpypi%2Fscikit-gof&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=NMDaYReA4O8IMIr4fgTCYPGD985SQjWxHA6mJs5VzB0%3D&reserved=0>
> As I said, I haven't dug into the code at all to see how it works, @rongpu
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frongpu&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=wi%2BeK4A83MrgHE7yaZ4bJPVcPkE54gjJi7tBm4%2FB3%2BE%3D&reserved=0>
> used it in the p(z) KS, CvM, and AD tests, so I just basically copied that
> for the N(z) case.
>
> I also tried the scipy.stats.anderson_ksamp(sample1,sample2) function link
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fscipy%2Freference%2Fgenerated%2Fscipy.stats.anderson_ksamp.html&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=RN7pnZEWGZtLExfqKfWFJ6jK6oi6grB2qF%2B2YEooK0A%3D&reserved=0>,
> which tests if two samples are drawn from the same distribution. I tried
> comparing values drawn from the two Gaussians I used in my ipynb example
> and somehow got a negative value for the statistic, which panicked the
> p-value calculator and caused a math overflow because the p-value was
> greater than 10^4032, so I kinda have my doubts about that method for
> non-trivial distributions as well...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLSSTDESC%2FPZDC1paper%2Fissues%2F11%23issuecomment-329369588&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=szDGQhT%2B0kcP7x%2BYLl3t%2FCVhOIRMY2xAM2uiOFY4sR0%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC-lNcnqkS5MJKAMaFpXW1KIabUmMKZ9ks5siK7pgaJpZM4O98XZ&data=01%7C01%7Cjanewman%40pitt.edu%7Cc83fb203dc394ab0811008d4fb2b2139%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1&sdata=KGOsKk10PsT8zDUNxbyyQSKCjD%2FWronQiLCTFDuZd6g%3D&reserved=0>
> .
>



-- 
--------------------------------------------------------------------------------------------------------
Jeffrey Newman            Professor, U. Pittsburgh Dept. of Physics &
Astronomy
(412) 592-3853             www.phyast.pitt.edu/~janewman

**Comment by sschmidt23** [comment]
Yes, I noticed that the scipy.stats AD test only had three or four distributions to compare against, so my attempt at the N(z) metric using skgof could definitely be subject to this if skgof assumes that you are drawing from those limited number of distributions.  

But, in the p(z) test that Rongpu wrote, it is comparing the PIT values to a uniform distribution, and my example notebook with 60,000 samples from two Gaussians still gives a p-value of 3.e-6 when comparing PIT to uniform, which seems fishy, as I would assume it would work well for uniform, which is one of the worked distributions in other AD implementation.  That 60,000 sample example is in this aforementioned notebook:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest.ipynb
@rongpu can you shed any light on this, having looked at skgof more?

**Comment by rongpu** [comment]
I would caution against using the tests in scipy.stats. I tested KS, CvM and AD from scipy.stats, skgof, the goftest library in R and my own script for uniform distribution, and find that all except scipy.stats give consistent statistics, and skgof and goftest give consistent p-values. Here is the notebook that I did the tests: https://github.com/rongpu/PZDC1PaperScripts/blob/master/my_scripts/metrics_validation.ipynb

@sschmidt23 In the AD script that I wrote, any PIT value smaller than 0.005 or larger than 0.995 is removed by default. This was to prevent photo-z outliers from blowing up the AD statistic, but that also changes the sample distribution and thus the statistic. I run your notebook after removing the cut on PIT values, and the AD p-value is consistent with other statistics. 

Since we cannot avoid PIT values at ~0 or 1 in the actual data due to outliers, it's necessary to remove these values, but in doing that we have essentially changed the definition of the AD statistic, and the p-values from the routines are probably no longer relevant. CvM doesn't have this problem, and if we don't need both AD and CvM, I guess we could just use CvM.

**Comment by sschmidt23** [comment]
Ok, thanks, Rongpu, the notebook is helpful.  The cut on PIT values near 0 and 1 is worrisome to me, as different codes will have different numbers of objects removed by the PIT cut, so will this really be a fair comparison between the different photo-z methods?  What do others think?

**Comment by johannct** [comment]
@sschmidt23 re your worry, best is probably to try the cut out on the various catalogue. Ideally we would not make any cut beyond the definition of the input catalogue.

**Comment by johannct** [comment]
@rongpu did you notify scipy? the stats experts there are usually very responsive. Next week I will try to devote some time to setting myself up for running and understanding the scripts, on top of providing the skynet regressor. In the meantime I cannot say much beyond that.

**Comment by janewman-pitt-edu** [comment]
The cut near 0 and 1 is fine so long as you also track the fraction rejected (which should be predictable if the distribution is well represented).  Basically, the fractions that are too close to the edges of the grid are analogous to the outliers when you look at point estimates.

**Comment by sschmidt23** [comment]
Ok, if we phrase this as a catastrophic outlier cut and keep track of the numbers for each code then I think it works, and is also a nice quick estimator for which codes produce more catastrophic outliers.  We may have to play with the cut value a bit to make sure that it is stable for the range that we check.  Sound good to everyone?

**Comment by janewman-pitt-edu** [comment]
Sure, sounds fine to me.

jeff

On Sep 15, 2017, at 7:03 PM, Sam Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, if we phrase this as a catastrophic outlier cut and keep track of the numbers for each code then I think it works, and is also a nice quick estimator for which codes produce more catastrophic outliers. We may have to play with the cut value a bit to make sure that it is stable for the range that we check. Sound good to everyone?

**Comment by sschmidt23** [comment]
So I was testing this further, and I actually can only get a decent test statistic and p-value for *more inclusive cuts* than the ones that Rongpu has as defaults, including no cuts at all (when using a distribution that is just drawn from two Gaussians).  That is, cuts on PIT of PIT>0.005 and PIT<0.995 give a p-value of 8.7e-6, but PIT>0.001 and PIT<0.999 gives a p-value of 0.486, and for no cuts a p-value of 0.769 and much lower test statistic of 0.478.  This is the opposite behavior compared to what we've been talking about above in previous comments on this issue.  See this updated notebook for the test statistics with different values of vmin and vmax:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest.ipynb
I have 80,000 samples in the two Gaussians in my example script, so I don't think it's small numbers.  Any ideas on what is going on here?

**Comment by aimalz** [comment]
Sorry for being silent on this before.  I think inclusion of those outliers may be necessary for the normalization conditions of our test statistics, which would explain the behavior @sschmidt23 observed.  This won't surprise anyone, but I am generally in favor of eliminating cuts whenever possible and using all available information.

**Comment by janewman-pitt-edu** [comment]
That's pretty strange.  I don't think the two-Gaussians case is the right test case for robustness of the limits, though.  Anderson-Darling will totally blow up if _anything_ has a CDF value of 0 or 1, I believe, as the weights go to infinity there.  It's effectively undefined if anything lies outside its PDF.  It seems more reasonable to calculate a statistic for things that are within the PDF, and separately track the fraction of objects rejected (which should be 1% for 0.005/0.995 cuts in the ideal case -- one can trivially calculate p-values for that quantity) rather than using an unstable statistic.

**Comment by janewman-pitt-edu** [comment]
Where is testme.AD defined?

**Comment by janewman-pitt-edu** [comment]
Actually, I think the answer may be trivial, Sam.  If you are cutting off at percentiles vmin and vmax, you need to compare to a uniform distribution between vmin and vmax, not one between 0 and 1.

**Comment by sschmidt23** [comment]
Jeff got it right, that uniform wasn't defined over the proper interval: I didn't notice that AD function simply called scipy.stats.uniform(), I have now modified that to include loc and scale properly, and the AD statistic now looks good in all cases, as you can see in this notebook (same as the old one but now all the AD stat values and p-values look good):
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest_properuniform.ipynb
I totally agree that this is not the test for the outlier PIT values of 0.0 and 1.0, but I wanted to confirm that the code was performing correctly on idealized data first before we applied it to the more complex data from our photo-z results.  I think we're now at that point for p(z), I need to make a few modifications for the N(z) version to properly track the vmin and vmax cuts.
