### ISSUE TITLE
Comparisons with "true" PDFs

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/PZDC1paper#15]
I just realized that we sort of do have access to the true posterior PDFs, so we can run all our metrics on the individual PDFs as well.  Since we know the true redshifts of all the galaxies, we can find the global, multidimensional probability distribution in the space of redshift and magnitudes/colors (by interpolating the distribution of the full sample of galaxies in that space).  If we evaluate this (continuous) multidimensional probability distribution at the magnitudes/colors in the catalog, we will actually have the true posterior PDFs.  (This of course assumes the galaxies are dense enough in this space for a reasonable interpolation.)

**Comment by sschmidt23** [comment]
Is what you're describing basically Melissa Graham's KNN method, but run on the "true" magnitudes, i.e. before magnitude errors are added?  I would worry about how reliable these PDFs are for objects with magnitudes/colors at the extremes of the distributions.

**Comment by sschmidt23** [comment]
Hmm, or do we do it on the scattered magnitudes/colors?  If it's this latter case, then you can increase your number of objects by creating many realizations of each true galaxy with magnitude errors to better fill in the color space, particularly at the edges.

**Comment by aimalz** [comment]
It would have to be done on the scattered magnitudes/colors.  The reason KNN isn't great for estimating photo-z PDFs is (biased) sparsity of the training set, but if we artificially created a complete space (like if it were populated by the full dataset, possibly with bonus realizations), it ought to be technically correct.

**Comment by sschmidt23** [comment]
This does sound familiar, I think we talked about this once in the past.  And I do think the true p(z) should be estimated at the "true" position of the galaxy so the magnitude errors don't move you to a different portion of color space.

**Comment by aimalz** [comment]
Your mention of errors reminds me, it will have to be a distribution in the space of redshifts, magnitudes, and their errors, if that's an input to any of the codes.  So that's how the errors come into it and why adding additional realizations based on those errors sounds inappropriate.

This does have some possible failure modes, so perhaps we shouldn't implement it in the DC1 paper but instead ask for the DC2 folks to make it for us.  In particular, if the interpolation fails (due to sparse data in some portion of the redshift/magnitude/errors space or something else), it could be dangerously wrong to use it as the basis for a metric.  

(Also, in case I forget later, I think we'd have to divide out the true redshift distribution from the multidimensional space to not accidentally propagate it as a prior.)

**Comment by morriscb** [comment]
Talking to Sam in chat, another failure would be if one of the codes was able used or found information that we didn't put into determining the "true PDFs". This would then cause a code that used this information (assuming it broke a degeneracy in the data say) to look "worse" than a code that didn't included it. This would be an obviously incorrect interpretation. I think you're right Alex, about what needs to be included in determining the "true PDFs" but we'll need to think really carefully about include.

**Comment by aimalz** [comment]
Indeed, the space of redshifts/magnitudes/errors actually needs to be redshifts+data, where data is every available piece of information given in the catalog that could be used for a redshift estimate.  For cross-correlation redshifts, that would include positions, which would almost certainly be sparse enough to break it, so I don't know how we'd make true redshift PDFs for that.

**Comment by morriscb** [comment]
Considering for the clustering-zs we always need a collection of objects to estimate the clustering we should have a true N(z) to compare directly to so this shouldn't be as big of an issue.

**Comment by aimalz** [comment]
Fair point!

So, is this something we want to try to squeeze into the DC1 paper or should I just put in a paragraph describing the possibility and why we're not doing it (still an approximation, hard to validate, choices of catalog information, still might be too sparse)?  Either way, are you both okay with me making an issue over on the DC2 repo requesting the real thing?

**Comment by morriscb** [comment]
I think a paragraph about the points you list will be fine.

I'm not sure how the DC2 data will be able to provide us with these posteriors. It would depend largely on how the galaxies are pasted initially onto the large scale structure. It may just be something we have to do ourselves as you described above. That said it wouldn't hurt to ask what is possible from the DC2 data.

**Comment by morriscb** [comment]
Jus talked to Sam. Give us a bit of time think about it. He thinks this may be a bit of a most complex and larger ask of sims than would be clear in a github issue.

**Comment by sschmidt23** [comment]
Well, the CS group is busy working to get the protoDC2 catalog out by Oct 31st, so let's think about exactly what we need and make sure this is the direction that we want to go (using "true p(z)") before we ask in an issue.  Also, as Chris says, this may require a bit of explanation, I'm wondering if an email, or even a quick Zoom session/hangout might be a more efficient way to get the discussion started.

**Comment by janewman-pitt-edu** [comment]
The space certainly isn't dense for redshift vs. magnitudes.  Even in redshift vs. 1 magnitude + colors, it'll certainly be sparse at some level.  Crudely: you have 7 dimensions there, with ~60 million objects to sample it in a 300 sq deg region (which I believe is the spec for DC2).  If you're doing that on a grid, you can do about 13 bins per dimension to have on average one object per bin.  I think incorporating magnitude errors actually helps at some level by blurring out the region you should consider and making more points relevant...

**Comment by aimalz** [comment]
Re: sparsity, that settles it; this is a thing we would need to request of the DR2 team and not something we can hack together ourselves, now or eventually.  We can continue the conversation about how to do it over there.
