### ISSUE TITLE
General script update

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/PZDC1paper#17]
@sschmidt23, you mentioned some additional scripts in an email the other day.  Would it be possible for you to put them in a branch here as well?

**Comment by sschmidt23** [comment]
Hi @aimalz, the additional scripts are already in that directory, they are diagnostic checks that I created to check the Kolmogorov-Smirnoff values by computing the empirical CDFs for the distributions and finding the maximum distance (just numpy.amax of the vector of differences) and I confirmed that the skgof functions agreed with my values (I mentioned in an email that there appears to be a mistake in the p-value computation for the skgof functions, so I wanted to make sure that at least the easy to compute KS distances were correct).

The scripts are:
plot_PIT_CDF_KS.py
plot_NZ_CDF_KS_exact.py
plot_NZ_CDF_KS_approx.py (approx grabs the summed p(z) and kde spec-z from the NZPLOT_vectors.out file and only compares the summed grid values, and is only an approximation, while exact computes the full eCDF of the spec-z values from all 399,356 redshifts).

The plots generated by these scripts are also in the following directory at NERSC:
/global/projecta/projectdirs/lsst/groups/PZ/PhotoZDC1/photoz_results

**Comment by sschmidt23** [comment]
And if anyone is curious about the skgof p-value problem, I made a quick ipynb showing the problem [here](https://github.com/sschmidt23/PZDC1_qptests/blob/master/testKSCvMAD_pvals_shiftGaussian_noADcut.ipynb).

**Comment by aimalz** [comment]
Great, sorry for not checking first.  I got thrown off when you said people should contact you individually if they wanted to see them but now see there's a separate folder for [plotting scripts](https://github.com/LSSTDESC/PZDC1paper/tree/pz_metrics).
