### ISSUE TITLE
Formatting bugs in authors.csv

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/PZDC1paper#22]
I had to pare down the `authors.csv` file during the desc-tex migration because there are formatting bugs in some entries.  Would someone smarter than me mind setting up a linter to find and fix them?  Thanks.

**Comment by sschmidt23** [comment]
I took a look, there was a funny parentheses in Brescia's entry that I fixed.  And for some reason it does not like either of Matt Jarvis' entries in authors.csv.  I cannot figure out why this is, so my temporary solution was to move his entry to the end and comment it out.  The version in the branch I created can now successfully be run for make authlist style=mnras 
I'll take another look later tonight or tomorrow, if I figure out what the problem with Matt's entry is, I'll issue a PR.

**Comment by sschmidt23** [comment]
I should add that this version does not reflect final author ordering, in case anyone else takes a look at this issue.  I will be taking a look at author ordering once we near the end of the responses to the internal referees.

**Comment by sschmidt23** [comment]
Missed the obvious "Contributor" as author type in Jarvis' two entries.  Those are now fixed and running make authlist now works.  There are still several authors who have not filled out their entries, but we can deal with that when we do the final "opt in" author review.  I'll create a pull request to merge this back in.

**Comment by aimalz** [comment]
This still doesn't work.  See #32.

**Comment by sschmidt23** [comment]
Ah, the version that you had pushed did not include a \maketitlepre, so the rendering of authors.tex didn't occur, the file was created with faulty latex.  Namely, the problem was a couple of "&" symbols in department names.  Easy fix with "\&" and it now runs for all authors.

**Comment by sschmidt23** [comment]
I see CMU is slightly different for P. Freeman, A. Lee, etc..., and is listed several times, I will go through and check people from the same institution in the near future to eliminate duplicates.

**Comment by sschmidt23** [comment]
Fixed the duplicate entries for UW, LUPM, CMU, and UC Davis, added missing USA to affiliations, and put external collaborator person at the end.
