### ISSUE TITLE
qp.PDF approximate and evaluate return NaN for Samples if min or max value has multiple entries

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#3]
qp.PDF() objects using approximate and evaluate return NaN outside the region of support if Samples are used and if the min or max value has multiple entries that are the same value.  This is due to scipy.interp.interp1d and fill_value="extrapolate", where it fails to estimate a slope at the end point, breaking extrapolation.  This should be fixable by setting fill_value = zero or a tiny number when using samples.

**Comment by drphilmarshall** [comment]
Hi @sschmidt23 - @aimalz is out sick right now - maybe try the suggested
fix in a patch branch of qp and if it works, submit a PR?

**Comment by aimalz** [comment]
I'm closing this issue since it's a problem with qp, not with the DC1 scripts.  Further discussion should happen over at [#78](https://github.com/aimalz/qp/issues/78) on qp.

**Comment by aimalz** [comment]
@sschmidt23 [`issue/78/extrapolation`](https://github.com/aimalz/qp/tree/issue/78/extrapolation) now includes a fix for this bug.  It should be merged into `master` as soon as @drphilmarshall can review [#81](https://github.com/aimalz/qp/pull/81).
