### ISSUE TITLE
Create working script for Kolmogorov-Smirnoff test

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#7]
Has this script been finalized?
Has it been uploaded to the PZDC1paper repository?

**Comment by sschmidt23** [comment]
I have tested the KS test scripts both on real data and on a simple set of two samples drawn from Gaussians.  For p(z) here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest.ipynb
and for N(z) here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/nz_stats_fakedatatest.ipynb

So, I'm fairly satisfied that this can be closed, though someone else please review the code and notebooks to confirm.

**Comment by aimalz** [comment]
(See comment [here](https://github.com/LSSTDESC/PZDC1paper/issues/9#issuecomment-332565368).)

**Comment by sschmidt23** [comment]
and response [here](https://github.com/LSSTDESC/PZDC1paper/issues/9#issuecomment-332565368) as well
