### ISSUE TITLE
Create working script for Cramer von Mises

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/PZDC1paper#9]
Has this script been finalized?
Has it been uploaded to the PZDC1paper repository?

**Comment by sschmidt23** [comment]
I have tested the CvM test scripts both on real data and on a simple set of two samples drawn from Gaussians. For p(z) here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/pz_stats_fakedatatest.ipynb
and for N(z) here:
https://github.com/sschmidt23/PZDC1_qptests/blob/master/nz_stats_fakedatatest.ipynb

So, I'm fairly satisfied that this can be closed, though someone else please review the code and notebooks to confirm.

**Comment by aimalz** [comment]
Looks good @sschmidt23!  Would you like to add these notebooks or a similar script to a branch in this repository and submit a pull request with reviewer(s) of your choice?

**Comment by sschmidt23** [comment]
Done.  I've added a comparison to real data from BPZ as well, for tests of performance with the excess catastrophic outliers with PIT values of 0.0 and 1.0.  See pull request here: [https://github.com/LSSTDESC/PZDC1paper/pull/12](https://github.com/LSSTDESC/PZDC1paper/pull/12)

Note that this notebook only covers the p(z) metrics, not the N(z) metrics.  I need to make a few changes to the N(z) code to make sure that the PDF object in the Anderson Darling test is properly normalized over the vmin-vmax range before I issue a pull request for the N(z) tests of KS/CvM/AD.
